
note.html: note.md
	lowdown -sthtml -m css:style.css -m javascript:https://polyfill.io/v3/polyfill.min.js?features=es6 -m javascript:https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js --parse-math note.md -o note.html
